services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    volumes:
      - mydb1:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: db
    volumes:
      - mydb2:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mydb1:
  mydb2:
